import { NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import { hasActivePro } from '@/lib/billing';
import { prisma } from '@/lib/prisma';
import { assertPublicOutboundUrl } from '@/lib/safe-outbound';

const MAX_FEEDS = Number(process.env.PRO_RSS_MAX_FEEDS_PER_USER || 10);
const REFRESH_COOLDOWN = Number(process.env.RSS_MANUAL_REFRESH_COOLDOWN_MINUTES || 15) * 60_000;
async function requirePro(request: Request) {
  const user = await getCurrentUser(request); if (!user) return { error: '请登录后管理 RSS。', status: 401 as const };
  const account = await prisma.user.findUnique({ where: { id: user.id }, select: { planType: true, proAccessExpiresAt: true } }); if (!hasActivePro(account || {})) return { error: '添加和管理个人 RSS 需要有效 Pro 专业权益。', status: 403 as const };
  return { user };
}
export async function GET(request: Request) { const result = await requirePro(request); if ('error' in result) return NextResponse.json({ error: result.error }, { status: result.status }); return NextResponse.json({ feeds: await prisma.rssFeed.findMany({ where: { ownerUserId: result.user.id, sourceType: 'USER' }, orderBy: { createdAt: 'desc' } }) }); }
export async function POST(request: Request) { const result = await requirePro(request); if ('error' in result) return NextResponse.json({ error: result.error }, { status: result.status }); try { const body = await request.json(); const name = String(body.name || '').trim().slice(0, 80); const url = String(body.url || '').trim(); if (!name || !url) return NextResponse.json({ error: 'RSS 名称和地址不能为空。' }, { status: 400 }); await assertPublicOutboundUrl(url, { requireHttps: process.env.NODE_ENV === 'production' }); const count = await prisma.rssFeed.count({ where: { ownerUserId: result.user.id, sourceType: 'USER' } }); if (count >= MAX_FEEDS) return NextResponse.json({ error: `每个 Pro 用户最多添加 ${MAX_FEEDS} 个 RSS 源。` }, { status: 400 }); return NextResponse.json({ feed: await prisma.rssFeed.create({ data: { ownerUserId: result.user.id, sourceType: 'USER', name, url } }) }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'RSS 地址不符合安全要求。' }, { status: 400 }); } }
export async function PATCH(request: Request) { const result = await requirePro(request); if ('error' in result) return NextResponse.json({ error: result.error }, { status: result.status }); const body = await request.json(); const id = String(body.id || ''); const feed = await prisma.rssFeed.findFirst({ where: { id, ownerUserId: result.user.id, sourceType: 'USER' } }); if (!feed) return NextResponse.json({ error: 'RSS 源不存在。' }, { status: 404 }); if (body.refresh) { if (feed.lastManualRefreshAt && Date.now() - feed.lastManualRefreshAt.getTime() < REFRESH_COOLDOWN) return NextResponse.json({ error: 'RSS 手动刷新过于频繁，请稍后重试。' }, { status: 429 }); return NextResponse.json({ feed: await prisma.rssFeed.update({ where: { id }, data: { lastManualRefreshAt: new Date() } }) }); } return NextResponse.json({ feed: await prisma.rssFeed.update({ where: { id }, data: { name: body.name ? String(body.name).trim().slice(0, 80) : undefined, isEnabled: typeof body.isEnabled === 'boolean' ? body.isEnabled : undefined } }) }); }
export async function DELETE(request: Request) { const result = await requirePro(request); if ('error' in result) return NextResponse.json({ error: result.error }, { status: result.status }); const id = new URL(request.url).searchParams.get('id') || ''; const deleted = await prisma.rssFeed.deleteMany({ where: { id, ownerUserId: result.user.id, sourceType: 'USER' } }); return deleted.count ? NextResponse.json({ ok: true }) : NextResponse.json({ error: 'RSS 源不存在。' }, { status: 404 }); }
